# Generated by Django 6.0 on 2025-12-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delivery_rider',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField()),
                ('rider_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PICKED', 'Picked'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delivery_assignment',
                'indexes': [models.Index(fields=['order_id'], name='delivery_as_order_i_73a6e2_idx')],
            },
        ),
    ]
